services:
  - type: web
    name: unified-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 120
      - key: DATABASE_URL
        fromDatabase:
          name: gpaydb
          property: connectionString
    autoDeploy: true

databases:
  - name: gpaydb
