services:
  - type: web
    name: gpay-fastapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gpaydb
          property: connectionString
databases:
  - name: gpaydb
